name: Generate pages

permissions:
  actions: write
  checks: write
  contents: write
  statuses: write
  pages: write
  id-token: write

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          ref: 'main'

      - name: create env file
        run: |
          touch .env
          echo RUDDERSTACK_KEY=${{ secrets.RUDDERSTACK_KEY }} >> .env
          echo RUDDERSTACK_URL=${{ secrets.RUDDERSTACK_URL }} >> .env
          echo GROWTHBOOK_API_HOST=${{ secrets.GROWTHBOOK_API_HOST }} >> .env
          echo GROWTHBOOK_CLIENT_KEY=${{ secrets.GROWTHBOOK_CLIENT_KEY }} >> .env
      - name: Generate Pages
        run: |
          git checkout main

          npm install
          current_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          echo "Running the generate pages script"

          cd $(git rev-parse --show-toplevel)
          npm run generate-pages
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: "./pages"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
      
