name: Generate and push Crowdin translations

permissions:
  actions: write
  checks: write
  contents: write
  pull-requests: write
  statuses: write

on:
  schedule:
    - cron: "0 */12 * * *" # Every 12 hours - https://crontab.guru/#0_*/12_*_*_*
  push:
    branches: [main]

jobs:
  crowdin:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}


      - name: Extract translations from templates
        run: |
          npm install
          echo "Running the translation script (extract-translations.js)"
          cd $(git rev-parse --show-toplevel)/scripts
          node extract-translations.js
          new_messages_json_hash="$(git hash-object $(git rev-parse --show-toplevel)/crowdin/messages.json)"
          echo "- [generated]: message.json hash is $new_messages_json_hash"

     

      - name: Generate Pages
        run: |
          current_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          echo "Running the generate pages script (generate-translations.js)"

          cd $(git rev-parse --show-toplevel)/scripts
          node generate-translations.js
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: l10n_crowdin_translations

