name: Generate and push Crowdin translations

permissions:
  actions: write
  checks: write
  contents: write
  pull-requests: write
  statuses: write

on:
  schedule:
    - cron: "0 */12 * * *" # Every 12 hours - https://crontab.guru/#0_*/12_*_*_*
  push:
    branches: [main]

jobs:
  crowdin:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract translations from templates
        run: |
          npm install
          echo "Running the translation script (extract-translations.js)"
          cd $(git rev-parse --show-toplevel)/scripts
          node extract-translations.js
          new_messages_json_hash="$(git hash-object $(git rev-parse --show-toplevel)/crowdin/messages.json)"
          echo "- [generated]: message.json hash is $new_messages_json_hash"

      - name: Synchronize with Crowdin
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: true
          download_translations: true
          localization_branch_name: l10n_crowdin_translations

          create_pull_request: true
          pull_request_title: "translations: 📚 sync translations with crowdin"
          pull_request_body: "translations: 📚 sync translations with crowdin"
          pull_request_base_branch_name: "main"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
    
      - name: Generate Pages
        run: |
          echo "Running the generate pages script (generate-translations.js)"
          cd $(git rev-parse --show-toplevel)/scripts
          node generate-translations.js
          git add .
          git commit -m "translations: 📚 generate and update pages"
          # Force push to this branch in case a previous run created it.
          git push --set-upstream origin "main" -f
