name: Generate pages

permissions:
  actions: write
  checks: write
  contents: write
  pull-requests: write
  statuses: write

on:
  workflow_run:
    workflows: ["Sync Translations"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          path: 'translations/l10n_crowdin'

      - name: Generate Pages
        run: |
          npm install
          current_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          echo "Running the generate pages script (generate-translations.js)"

          cd $(git rev-parse --show-toplevel)/scripts
          node generate-translations.js

          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git commit -am "Update pages ${current_date}"
          git push
